version: "3.9" 
services:
  cataso:
    build:
        context: .
        dockerfile: Dockerfile.node
    restart: always
    environment:
        TZ: Asia/Tokyo
    volumes:
        - .:/workspace
  nginx:
    image: nginx
    ports:
        - "443:443"
    environment:
        TZ: Asia/Tokyo
    volumes:
        - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
        - ./cert/privkey.pem:/etc/ssl/private/server.key
        - ./cert/server.crt:/etc/ssl/certs/server.crt
